# .streamlit/config.toml

[theme]
base="dark"
primaryColor="#4e128e"
backgroundColor="#233467"
textColor="#f5f2f5"
font="monospace"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
